INSERT INTO lost_found_items (title, description, category, location, dateLostFound, contactInfo, status) VALUES
('Lost Wallet', 'Black leather wallet with several cards and cash', 'Accessories', 'Library', '2024-06-01', 'contact1@example.com', 'lost'),
('Found Keys', 'Set of car and house keys with a red keychain', 'Keys', 'Cafeteria', '2024-06-02', 'contact2@example.com', 'found'),
('Lost Phone', 'iPhone 12 with cracked screen', 'Electronics', 'Bus Stop', '2024-05-30', 'contact3@example.com', 'lost'),
('Found Backpack', 'Blue backpack with school books inside', 'Bags', 'Main Entrance', '2024-06-03', 'contact4@example.com', 'found'),
('Lost Jacket', 'Black winter jacket with fur hood', 'Clothing', 'Gym', '2024-05-28', 'contact5@example.com', 'lost'),
('Found Glasses', 'Pair of reading glasses in a black case', 'Accessories', 'Lecture Hall', '2024-06-01', 'contact6@example.com', 'found'),
('Lost Watch', 'Silver wristwatch with leather strap', 'Accessories', 'Parking Lot', '2024-05-29', 'contact7@example.com', 'lost'),
('Found Umbrella', 'Black umbrella with wooden handle', 'Accessories', 'Cafeteria', '2024-06-02', 'contact8@example.com', 'found'),
('Lost Notebook', 'Red notebook with math notes', 'Stationery', 'Library', '2024-05-31', 'contact9@example.com', 'lost'),
('Found Water Bottle', 'Green water bottle with stickers', 'Accessories', 'Sports Field', '2024-06-03', 'contact10@example.com', 'found'),
('Lost Earphones', 'White wireless earphones', 'Electronics', 'Bus Stop', '2024-05-30', 'contact11@example.com', 'lost'),
('Found Scarf', 'Blue knitted scarf', 'Clothing', 'Main Entrance', '2024-06-01', 'contact12@example.com', 'found'),
('Lost ID Card', 'Student ID card with photo', 'Documents', 'Library', '2024-05-29', 'contact13@example.com', 'lost'),
('Found Wallet', 'Brown leather wallet with coins', 'Accessories', 'Cafeteria', '2024-06-02', 'contact14@example.com', 'found'),
('Lost Sunglasses', 'Black sunglasses with UV protection', 'Accessories', 'Gym', '2024-05-28', 'contact15@example.com', 'lost'),
('Found Phone Charger', 'White phone charger cable', 'Electronics', 'Lecture Hall', '2024-06-03', 'contact16@example.com', 'found'),
('Lost Backpack', 'Green backpack with laptop inside', 'Bags', 'Parking Lot', '2024-05-30', 'contact17@example.com', 'lost'),
('Found Jacket', 'Red rain jacket', 'Clothing', 'Sports Field', '2024-06-01', 'contact18@example.com', 'found'),
('Lost Book', 'Textbook on computer science', 'Books', 'Library', '2024-05-31', 'contact19@example.com', 'lost'),
('Found Keys', 'Set of house keys with blue keychain', 'Keys', 'Main Entrance', '2024-06-02', 'contact20@example.com', 'found'),
('Lost Calculator', 'Scientific calculator', 'Electronics', 'Lecture Hall', '2024-05-29', 'contact21@example.com', 'lost'),
('Found Notebook', 'Black notebook with sketches', 'Stationery', 'Cafeteria', '2024-06-03', 'contact22@example.com', 'found'),
('Lost Gloves', 'Pair of black gloves', 'Clothing', 'Bus Stop', '2024-05-28', 'contact23@example.com', 'lost'),
('Found Hat', 'Blue baseball cap', 'Clothing', 'Gym', '2024-06-01', 'contact24@example.com', 'found'),
('Lost ID Badge', 'Employee ID badge', 'Documents', 'Parking Lot', '2024-05-30', 'contact25@example.com', 'lost'),
('Found Wallet', 'Black wallet with ID cards', 'Accessories', 'Library', '2024-06-02', 'contact26@example.com', 'found'),
('Lost Phone Case', 'Red phone case', 'Accessories', 'Lecture Hall', '2024-05-31', 'contact27@example.com', 'lost'),
('Found Earphones', 'Wireless earphones in case', 'Electronics', 'Cafeteria', '2024-06-03', 'contact28@example.com', 'found'),
('Lost Water Bottle', 'Blue water bottle', 'Accessories', 'Sports Field', '2024-05-29', 'contact29@example.com', 'lost'),
('Found Sunglasses', 'Brown sunglasses', 'Accessories', 'Main Entrance', '2024-06-01', 'contact30@example.com', 'found'),
('Lost Jacket', 'Grey jacket with hood', 'Clothing', 'Library', '2024-05-30', 'contact31@example.com', 'lost'),
('Found Gloves', 'Black gloves', 'Clothing', 'Gym', '2024-06-02', 'contact32@example.com', 'found'),
('Lost Book', 'Novel book', 'Books', 'Bus Stop', '2024-05-31', 'contact33@example.com', 'lost'),
('Found Calculator', 'Calculator with case', 'Electronics', 'Lecture Hall', '2024-06-03', 'contact34@example.com', 'found'),
('Lost Scarf', 'Red scarf', 'Clothing', 'Parking Lot', '2024-05-29', 'contact35@example.com', 'lost'),
('Found ID Card', 'Student ID card', 'Documents', 'Cafeteria', '2024-06-01', 'contact36@example.com', 'found'),
('Lost Keys', 'Set of car keys', 'Keys', 'Library', '2024-05-30', 'contact37@example.com', 'lost'),
('Found Phone', 'Smartphone found', 'Electronics', 'Main Entrance', '2024-06-02', 'contact38@example.com', 'found'),
('Lost Backpack', 'Black backpack', 'Bags', 'Gym', '2024-05-31', 'contact39@example.com', 'lost'),
('Found Jacket', 'Blue jacket', 'Clothing', 'Bus Stop', '2024-06-03', 'contact40@example.com', 'found'),
('Lost Wallet', 'Leather wallet', 'Accessories', 'Parking Lot', '2024-05-29', 'contact41@example.com', 'lost'),
('Found Notebook', 'Notebook with notes', 'Stationery', 'Cafeteria', '2024-06-01', 'contact42@example.com', 'found'),
('Lost Phone', 'Android phone', 'Electronics', 'Library', '2024-05-30', 'contact43@example.com', 'lost'),
('Found Gloves', 'Pair of gloves', 'Clothing', 'Gym', '2024-06-02', 'contact44@example.com', 'found'),
('Lost Sunglasses', 'Sunglasses with case', 'Accessories', 'Bus Stop', '2024-05-31', 'contact45@example.com', 'lost'),
('Found Water Bottle', 'Water bottle found', 'Accessories', 'Main Entrance', '2024-06-03', 'contact46@example.com', 'found'),
('Lost Calculator', 'Old calculator', 'Electronics', 'Parking Lot', '2024-05-29', 'contact47@example.com', 'lost'),
('Found Book', 'Book found', 'Books', 'Cafeteria', '2024-06-01', 'contact48@example.com', 'found'),
('Lost Hat', 'Black hat', 'Clothing', 'Library', '2024-05-30', 'contact49@example.com', 'lost'),
('Found ID Badge', 'Employee ID badge', 'Documents', 'Gym', '2024-06-02', 'contact50@example.com', 'found');
